// Generated by tooling/scripts/generate-theme-bridge.ts.
// Do not edit by hand.
//
// Reusables / React Navigation compat layer. Runtime theming uses Uniwind + applyMobileTheme().

import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: "#111a2b",
    foreground: "#e6edf7",
    card: "#16233a",
    cardForeground: "#e6edf7",
    popover: "#16233a",
    popoverForeground: "#e6edf7",
    primary: "#3f79d8",
    primaryForeground: "#f4f8ff",
    secondary: "#22334f",
    secondaryForeground: "#e6edf7",
    muted: "#1c2a43",
    mutedForeground: "#a9b8cf",
    accent: "#2a4060",
    accentForeground: "#e6edf7",
    destructive: "#b74a56",
    border: "#304867",
    input: "#304867",
    ring: "#5f8fdd",
    radius: "0.625rem",
    chart1: "#3f79d8",
    chart2: "#4f92e2",
    chart3: "#5aaad8",
    chart4: "#c1964a",
    chart5: "#6bb48b",
  },
  dark: {
    background: "#111a2b",
    foreground: "#e6edf7",
    card: "#16233a",
    cardForeground: "#e6edf7",
    popover: "#16233a",
    popoverForeground: "#e6edf7",
    primary: "#3f79d8",
    primaryForeground: "#f4f8ff",
    secondary: "#22334f",
    secondaryForeground: "#e6edf7",
    muted: "#1c2a43",
    mutedForeground: "#a9b8cf",
    accent: "#2a4060",
    accentForeground: "#e6edf7",
    destructive: "#b74a56",
    border: "#304867",
    input: "#304867",
    ring: "#5f8fdd",
    radius: "0.625rem",
    chart1: "#3f79d8",
    chart2: "#4f92e2",
    chart3: "#5aaad8",
    chart4: "#c1964a",
    chart5: "#6bb48b",
  },
} as const;

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: "#111a2b",
      border: "#304867",
      card: "#16233a",
      notification: "#b74a56",
      primary: "#3f79d8",
      text: "#e6edf7",
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: "#111a2b",
      border: "#304867",
      card: "#16233a",
      notification: "#b74a56",
      primary: "#3f79d8",
      text: "#e6edf7",
    },
  },
};
