/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.tsx",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./lib/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "../../packages/shared/src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        /* GENERATED:theme-bridge:start */
        "surface-0": "var(--surface-0)",
        "surface-1": "var(--surface-1)",
        "surface-2": "var(--surface-2)",
        "surface-3": "var(--surface-3)",
        "surface-3b": "var(--surface-3b)",
        "surface-4": "var(--surface-4)",
        "surface-5": "var(--surface-5)",
        "surface-destructive-soft": "var(--surface-destructive-soft)",
        "surface-list-hover": "var(--surface-list-hover)",
        "surface-message-row": "var(--surface-message-row)",
        "surface-message-row-hover": "var(--surface-message-row-hover)",
        "surface-destructive-panel": "var(--surface-destructive-panel)",
        "border-subtle": "var(--border-subtle)",
        "border-default": "var(--border-default)",
        "primary": "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        "primary-hover": "var(--primary-hover)",
        "destructive": "var(--destructive)",
        "destructive-hover": "var(--destructive-hover)",
        "destructive-foreground": "var(--destructive-foreground)",
        "ring": "var(--ring)",
        "ring-focus": "var(--ring-focus)",
        "link": "var(--link)",
        "link-hover": "var(--link-hover)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        "text-muted": "var(--text-muted)",
        "text-dim": "var(--text-dim)",
        "text-info": "var(--text-info)",
        "text-destructive-soft": "var(--text-destructive-soft)",
        "text-destructive-banner": "var(--text-destructive-banner)",
        "text-avatar-fallback": "var(--text-avatar-fallback)",
        "text-link-bright": "var(--text-link-bright)",
        "text-link-soft": "var(--text-link-soft)",
        "text-attachment-label": "var(--text-attachment-label)",
        "text-form-label": "var(--text-form-label)",
        "text-chip-muted": "var(--text-chip-muted)",
        "text-notification-link": "var(--text-notification-link)",
        "text-notification-soft": "var(--text-notification-soft)",
        "text-send-error": "var(--text-send-error)",
        "text-hub-warm": "var(--text-hub-warm)",
        "text-embed-chip": "var(--text-embed-chip)",
        "text-success": "var(--text-success)",
        "status-online": "var(--status-online)",
        "status-away": "var(--status-away)",
        "status-dnd": "var(--status-dnd)",
        "discord-blurple": "var(--discord-blurple)",
        "accent-amber": "var(--accent-amber)",
        "accent-slider": "var(--accent-slider)",
        "accent-success": "var(--accent-success)",
        "background": "var(--background)",
        "foreground": "var(--foreground)",
        "card": "var(--card)",
        "card-foreground": "var(--card-foreground)",
        "popover": "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        "secondary": "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        "muted": "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        "accent": "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        "border": "var(--border)",
        "input": "var(--input)",
        "surface-app": "var(--surface-app)",
        "surface-modal": "var(--surface-modal)",
        "surface-input": "var(--surface-input)",
        "surface-legal": "var(--surface-legal)",
        "surface-desktop-shell": "var(--surface-desktop-shell)",
        "surface-toast": "var(--surface-toast)",
        "surface-info": "var(--surface-info)",
        "surface-panel": "var(--surface-panel)",
        "surface-hover": "var(--surface-hover)",
        "surface-inset": "var(--surface-inset)",
        "surface-embedded": "var(--surface-embedded)",
        "surface-card-deep": "var(--surface-card-deep)",
        "surface-peek": "var(--surface-peek)",
        "surface-skeleton": "var(--surface-skeleton)",
        "surface-voice-scrim": "var(--surface-voice-scrim)",
        "surface-dm-row-hover": "var(--surface-dm-row-hover)",
        "surface-role-hover": "var(--surface-role-hover)",
        "surface-row-selected": "var(--surface-row-selected)",
        "surface-footer-bar": "var(--surface-footer-bar)",
        "surface-embed-hover": "var(--surface-embed-hover)",
        "surface-attachment-hover": "var(--surface-attachment-hover)",
        "surface-embed-chip": "var(--surface-embed-chip)",
        "surface-row-active": "var(--surface-row-active)",
        "body-soft": "var(--body-soft)",
        "info": "var(--info)",
        "destructive-soft": "var(--destructive-soft)",
        "destructive-surface": "var(--destructive-surface)",
        "border-row": "var(--border-row)",
        "border-titlebar": "var(--border-titlebar)",
        "border-dialog": "var(--border-dialog)",
        "border-inset-panel": "var(--border-inset-panel)",
        "border-modmail": "var(--border-modmail)",
        "border-control": "var(--border-control)",
        "border-selected": "var(--border-selected)",
        "border-message-row": "var(--border-message-row)",
        "border-message-row-hover": "var(--border-message-row-hover)",
        "border-reply-thread": "var(--border-reply-thread)",
        "border-notification": "var(--border-notification)",
        "sidebar": "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
        "scrollbar-track": "var(--scrollbar-track)",
        "scrollbar-thumb": "var(--scrollbar-thumb)",
        "scrollbar-thumb-hover": "var(--scrollbar-thumb-hover)",
        "gradient-voice-0": "var(--gradient-voice-0)",
        "gradient-voice-1": "var(--gradient-voice-1)",
        "destructive-banner": "var(--destructive-banner)",
        "avatar-fallback": "var(--avatar-fallback)",
        "link-bright": "var(--link-bright)",
        "link-soft": "var(--link-soft)",
        "attachment-label": "var(--attachment-label)",
        "form-label": "var(--form-label)",
        "chip-muted": "var(--chip-muted)",
        "notification-link": "var(--notification-link)",
        "notification-soft": "var(--notification-soft)",
        "send-error": "var(--send-error)",
        "hub-warm": "var(--hub-warm)",
        "embed-chip": "var(--embed-chip)",
/* GENERATED:theme-bridge:end */
      },
    },
  },
  plugins: [],
};
