// Generated by tooling/scripts/generate-theme-bridge.ts.
// This mirrors apps/mobile/metro.config.js extraThemes for typechecking.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
  export interface UniwindConfig {
    themes: readonly ['light','dark','default','halloween','winter','midnight','forest','dracula','rose','nord','blood-moon','crypt','belmont','neon-noir','chrome','netrunner','nebula','void','aurora','forge','cinder','brassweld'];
  }
}

export {};
